### ISSUE TITLE
为啥我打开无法显示呢

### ISSUE THREAD

**Issue by zpzxgcr** [ZYSzys/vue-canvas-nest#2]
![_20180702175952](https://user-images.githubusercontent.com/16409424/42158006-cdc3ad6e-7e21-11e8-867f-df558019cec0.png)
![_ 20180702180028](https://user-images.githubusercontent.com/16409424/42158043-e8d1265e-7e21-11e8-8045-a2ce51e6005d.png)
@ZYSzys

**Comment by zpzxgcr** [comment]
![ddas _20180702181242](https://user-images.githubusercontent.com/16409424/42158709-d2bb5ef0-7e23-11e8-9e5e-797928c0cf59.png)

**Comment by ZYSzys** [comment]
应该是css的问题，我刚更新了，你试一下最新的版本 @zpzxgcr

**Comment by ZYSzys** [comment]
还不行的话应该是zindex问题，可以尝试修改下，越大越上层

**Comment by zpzxgcr** [comment]
你的是可以的吗  我按照你的要求来 了还是不行诶 @ZYSzys
