### ISSUE TITLE
在特定的区域显示时，鼠标位置不会在特定的位置

### ISSUE THREAD

**Issue by ggzzddd** [ZYSzys/vue-canvas-nest#22]

**Comment by ZYSzys** [comment]
@ggzzddd 试一下新版本v2.0.0

**Comment by ggzzddd** [comment]
@ZYSzys 
![canvas](https://user-images.githubusercontent.com/40220868/44616150-2f22fa80-a87d-11e8-9cdb-db12f070781b.gif)当做模块来用的使用会出现这种问题

**Comment by ZYSzys** [comment]
看上去好像是定位问题。能贴一些示例代码吗

**Comment by ggzzddd** [comment]
@ZYSzys [https://github.com/ggzzddd/vue-canvas-demo](url)我建立了一个重现的demo项目

**Comment by ZYSzys** [comment]
可以这样使用 [demo](https://github.com/ggzzddd/vue-canvas-demo/pull/1/files)

**Comment by ggzzddd** [comment]
1. 这样鼠标的位置是可以获取了，这样写的原理是什么能解释下吗？万分感谢！
2. 在鼠标在划出这个内容区域的边界时能不能解除掉鼠标事件呢？这样体验是不是更好呢。

**Comment by ggzzddd** [comment]
非常感谢！
