### ISSUE TITLE
为什么我按照教程中的引入了之后没有生效

### ISSUE THREAD

**Issue by DoGoodMore** [ZYSzys/vue-canvas-nest#5]
import vueCanvasNest from 'vue-canvas-nest' ;
components: { vueCanvasNest },
在data中定义了配置对象
data() {
    return {
       vueCanvasNestConfig: {
                    zIndex: 2
                }
    }
}
再调用时候传入进去
<vue-canvas-nest :config="vueCanvasNestConfig"></vue-canvas-nest>

在页面中已经有了这个元素 但是我的配置对象并没有生效

**Comment by ZYSzys** [comment]
当前组件是否设置了背景把canvas-nest给遮住了呢？

**Comment by ZYSzys** [comment]
https://github.com/hustcc/canvas-nest.js/issues/15
https://github.com/hustcc/canvas-nest.js/issues/31
